#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ztk_service[-1]
	add ucitrack ztk_service
        set ucitrack.@ztk_service[-1].init=ztk_service
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
