#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@sub-ghz[-1]
	add ucitrack sub-ghz
        set ucitrack.@sub-ghz[-1].init=sub-ghz
#        add_list ucitrack.@sub-ghz[0].init=sub-ghz
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
